import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { Fragment } from "react";

import { RiBookMarkFill } from "react-icons/ri";
import AddBook from "../components/add-book";
import Book from "../components/shared/book";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  // const hello = trpc.example.hello.useQuery({ text: "from tRPC" });
  const books = trpc.books.getAll.useQuery();

  const router = useRouter();

  const AddBookClickHandler = () => {
    router.push("/add-book");
  };

  return (
    <Fragment>
      <Head>
        <title>Prisha Policy</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-1 xs:px-4 sm:px-10">
        <div className="mt-20 flex items-center gap-4 text-5xl text-primary">
          <RiBookMarkFill />
          <h1 className="font-semibold "> My Books</h1>
        </div>

        <div className="mx-auto mt-4 grid grid-cols-2 xs:grid-cols-3 sm:gap-4 min-[800px]:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6 2xl:grid-cols-7">
          {books.data?.map((el) => {
            return <Book key={el.id} book={el} />;
          })}
          {/* <Book />
          <Book />
          <Book />
          <Book />
          <Book />
          <Book />
          <Book />
          <Book />
          <Book />
          <Book />
          <Book />
          <Book />
          <Book /> */}
          <AddBook onClick={AddBookClickHandler} />
        </div>
      </main>
    </Fragment>
  );
};

export default Home;
